version: "3.8"

services:
  influxdb:
    build:
      context: ./influxdb/
    container_name: ${CONTAINER_PREFIX}_influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    restart: on-failure:10
    ports:
      - ${INFLUXDB_PORT:-8086}:8086
      - "8083:8083"
    networks:
      - spauto_devnet_default

  telegraf:
    build:
      context: ./telegraf/
    container_name: ${CONTAINER_PREFIX}_telegraf
    privileged: true
    restart: always
    volumes:
      - ${TELEGRAF_CFG_PATH:-./telegraf/telegraf.conf}:/etc/telegraf/telegraf.conf
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - spauto_devnet_default
    ports:
      - ${TELEGRAF_PORT:-42518}:42518

  grafana:
    build:
      context: ./grafana/
    container_name: ${CONTAINER_PREFIX}_grafana
    restart: always
    privileged: true
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    networks:
      - spauto_devnet_default
    env_file:
      - .env

volumes:
  grafana-storage:
  influxdb-storage:


networks:
  spauto_devnet_default:
    external: true
