[tool.poetry]
name = "mpls_in_the_sdn_era"
version = "0.1.0"
description = ""
authors = ["h4ndzdatm0ld <hugotinoco@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ncclient = "^0.6.10"
netmiko = "^3.3.3"
nornir-utils = "^0.1.2"
nornir-netmiko = "^0.1.1"
nornir-jinja2 = "^0.1.2"
pynso = "^1.2.0"
prettyprint = "^0.1.5"
ipython = "^7.22.0"
yamllint = "^1.26.1"
PyYAML = "^5.4.1"
pybatfish = "^2021.2.26"
pydocstyle = "^6.0.0"
pybandit = "^0.0.1"
flake8 = "^3.9.0"
black = "^20.8b1"
bandit = "^1.7.0"
pytest = "^6.2.3"
napalm = "^3.2.0"
nornir-napalm = "^0.1.2"
pyIOSXR = "^0.53"
docker = "^5.0.0"
ntc-templates = "^2.0.0"
ansible = "^3.3.0"
xmltodict = "^0.12.0"
jxmlease = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
