[tool.poetry]
name = "mpls_in_the_sdn_era"
version = "0.1.0"
description = ""
authors = ["h4ndzdatm0ld <hugotinoco@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ncclient = "^0.6.10"
netmiko = "^3.3.3"
nornir-utils = "^0.1.2"
nornir-netmiko = "^0.1.1"
nornir-jinja2 = "^0.1.2"
pynso = "^1.2.0"
prettyprint = "^0.1.5"
ipython = "^7.22.0"
yamllint = "^1.26.1"
PyYAML = "^5.4.1"
pybatfish = "^2021.2.26"
pydocstyle = "^6.0.0"
pybandit = "^0.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
