---
# ansible_network_os: restconf
ansible_network_os: ios
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443
ansible_httpapi_restconf_root: "/restconf/data/"  # default
ansible_httpapi_use_ssl: true
# ansible_connection: "httpapi"
ansible_connection: network_cli
